apiVersion: v1
kind: Service
metadata:
  name: llm-react-frontend-svc
  namespace: demo
spec:
  type: NodePort
  selector:
    app: llm-react-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # 외부 공개 포트 (원하면 30000~32767 범위에서 조정 가능)
